// Lexique de phrases affichées aléatoirement sur l'écran de chargement
export const LOADING_PHRASES = [
    "Compilation des composants...",
    "Résolution des dépendances...",
    "Chargement des assets...",
    "Optimisation du build...",
    "Connexion au serveur...",
    "Initialisation du kernel...",
    "Mise en cache des ressources...",
    "Rendu des composants React...",
    "Synchronisation avec le cloud...",
    "Vérification de l'intégrité des fichiers...",
    "Démarrage des services...",
    "Chargement du portfolio...",
    "Injection des dépendances...",
    "Bootstrapping de l'application...",
    "Allocation de la mémoire...",
    "Exécution du garbage collector...",
    "Négociation TLS en cours...",
    "Indexation des articles du blog...",

    "Résolution d'un conflit Git à mains nues...",
    "Recherche du point-virgule manquant...",
    "Copier-coller depuis Stack Overflow...",
    "Ça marchait sur ma machine, patience...",
    "Désactivation du mode 'ça compile pas'...",
    "Renommage de variable en 'toto2_final_v3'...",
    "Suppression du node_modules (ça repousse vite)...",
    "Chasse aux bugs à mains nues...",
    "Résolution de bugs CSS...",
    "Redémarrage, ça résout tout...",
    "Lecture de la doc en diagonale...",
    "Un café, puis ça ira mieux...",
    "Débranchement et rebranchement du serveur...",
    "Ça marche sur ma machine...",

    "Réveil de Kylian après une soirée DJ...",
    "Kylian tente encore de parcourir Paris en courant...",
    "Chargement du charisme d'ingénieur de Kylian...",
    "Kylian répond enfin à ses mails...",
    "Un développeur n'est pas un dépanneur d'imprimante...",
    "Vérification que Kylian est réveillé...",
    "Mauvaise manip sur la prod en cours...",
    "Encore un merge conflict à résoudre...",
];