name: Build and Deploy Blog to OVH (FTP)

on:
  push:
    branches:
      - main
    paths:
      - 'src/assets/blogs/**'
      - 'src/assets/projects/**'
      - 'src/**'
      - 'package.json'

  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      # 1. Récupère le code
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Configure Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      # 3. Installe les dépendances
      - name: Install dependencies
        run: npm ci

      # 4. Génère l'index du blog
      - name: Generate blog index
        run: node generate-blog-index.mjs && node generate-project-index.mjs

      # 5. Build le projet Angular
      - name: Build Angular project
        run: npm run build -- --configuration production

      # 6. Déploie via FTP
      - name: Deploy to OVH via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./dist/kylianjulia/browser/
          server-dir: /www/  # Change selon ton hébergement OVH
          dangerous-clean-slate: false  # Ne supprime pas tout avant d'uploader
